---
name: Snapshot Manager CI
on: [push]
jobs:
  python-basic-tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Run apt-get update
        run: sudo apt-get -q update
      - name: Install Ubuntu deps
        run: >
          DEBIAN_FRONTEND=noninteractive
          sudo apt-get install -y
          python3-pytest
          python3-pycodestyle
          python3-coverage
          pycodestyle
          bandit
          lvm2
      - name: Install Snapshot Manager
        run: >
          sudo pip install -v .
      - name: Check out boom
        run: git clone https://github.com/snapshotmanager/boom
        working-directory: /var/tmp
      - name: Install boom
        run: sudo python3 setup.py install
        working-directory: /var/tmp/boom
      - name: Create boom configuration
        run: |
          sudo mkdir /boot/boom
          sudo mkdir /boot/boom/cache
          sudo mkdir /boot/boom/hosts
          sudo mkdir /boot/boom/profiles
          sudo mkdir -p /boot/loader/entries
          sudo cp /var/tmp/boom/examples/boom.conf /boot/boom
          # Create profiles for kernel variants seen in CI
          sudo boom profile create --from-host --uname-pattern generic
          sudo boom profile create --from-host --uname-pattern azure
      - name: Check PyCodestyle
        run: >
          pycodestyle snapm --ignore E501,E203,W503
      - name: Run bandit
        run: >
          bandit --skip B303,B404,B603 -r snapm
      - name: Run test suite with coverage
        run: >
          sudo python3-coverage run /usr/bin/pytest-3 --log-level=debug -v
      - name: Report coverage
        run: >
          python3-coverage report -m --include "./snapm/*"

